
let shirtOptions = {
    "Short Sleeve Shirts": {
        "xs": [
            {"dimension": "1x1", "price": 250},
            {"dimension": "1x2", "price": 250},
            {"dimension": "1x3", "price": 255},
            {"dimension": "1x4", "price": 255},
            {"dimension": "2x1", "price": 250},
            {"dimension": "2x2", "price": 260},
            {"dimension": "2x3", "price": 265},
            {"dimension": "2x4", "price": 265},
            {"dimension": "3x1", "price": 255},
            {"dimension": "3x2", "price": 265},
            {"dimension": "3x3", "price": 270},
            {"dimension": "3x4", "price": 275},
            {"dimension": "4x1", "price": 260},
            {"dimension": "4x2", "price": 270},
            {"dimension": "4x3", "price": 275},
            {"dimension": "4x4", "price": 280}
        ],
        "s": [
            {"dimension": "1x1", "price": 255},
            {"dimension": "1x2", "price": 255},
            {"dimension": "1x3", "price": 260},
            {"dimension": "1x4", "price": 265},
            {"dimension": "2x1", "price": 265},
            {"dimension": "2x2", "price": 270},
            {"dimension": "2x3", "price": 275},
            {"dimension": "2x4", "price": 280},
            {"dimension": "3x1", "price": 260},
            {"dimension": "3x2", "price": 265},
            {"dimension": "3x3", "price": 27},
            {"dimension": "3x4", "price": 275},
            {"dimension": "4x1", "price": 265},
            {"dimension": "4x2", "price": 270},
            {"dimension": "4x3", "price": 275},
            {"dimension": "4x4", "price": 280}
        ],
        "m": [
            {"dimension": "1x1", "price": 260},
            {"dimension": "1x2", "price": 260},
            {"dimension": "1x3", "price": 265},
            {"dimension": "1x4", "price": 270},
            {"dimension": "2x1", "price": 260},
            {"dimension": "2x2", "price": 265},
            {"dimension": "2x3", "price": 270},
            {"dimension": "2x4", "price": 275},
            {"dimension": "3x1", "price": 265},
            {"dimension": "3x2", "price": 270},
            {"dimension": "3x3", "price": 275},
            {"dimension": "3x4", "price": 280},
            {"dimension": "4x1", "price": 270},
            {"dimension": "4x2", "price": 275},
            {"dimension": "4x3", "price": 280},
            {"dimension": "4x4", "price": 285}
        ],
        "l": [
            {"dimension": "1x1", "price": 290},
            {"dimension": "1x2", "price": 295},
            {"dimension": "1x3", "price": 300},
            {"dimension": "1x4", "price": 305},
            {"dimension": "2x1", "price": 295},
            {"dimension": "2x2", "price": 300},
            {"dimension": "2x3", "price": 305},
            {"dimension": "2x4", "price": 310},
            {"dimension": "3x1", "price": 300},
            {"dimension": "3x2", "price": 305},
            {"dimension": "3x3", "price": 310},
            {"dimension": "3x4", "price": 315},
            {"dimension": "4x1", "price": 305},
            {"dimension": "4x2", "price": 310},
            {"dimension": "4x3", "price": 315},
            {"dimension": "4x4", "price": 320}
        ],
        "xl": [
            {"dimension": "1x1", "price": 295},
            {"dimension": "1x2", "price": 300},
            {"dimension": "1x3", "price": 305},
            {"dimension": "1x4", "price": 310},
            {"dimension": "2x1", "price": 300},
            {"dimension": "2x2", "price": 305},
            {"dimension": "2x3", "price": 310},
            {"dimension": "2x4", "price": 315},
            {"dimension": "3x1", "price": 305},
            {"dimension": "3x2", "price": 310},
            {"dimension": "3x3", "price": 315},
            {"dimension": "3x4", "price": 320},
            {"dimension": "4x1", "price": 310},
            {"dimension": "4x2", "price": 315},
            {"dimension": "4x3", "price": 320},
            {"dimension": "4x4", "price": 325}
        ],
        "2xl": [
            {"dimension": "1x1", "price": 300},
            {"dimension": "1x2", "price": 305},
            {"dimension": "1x3", "price": 310},
            {"dimension": "1x4", "price": 315},
            {"dimension": "2x1", "price": 305},
            {"dimension": "2x2", "price": 310},
            {"dimension": "2x3", "price": 315},
            {"dimension": "2x4", "price": 320},
            {"dimension": "3x1", "price": 310},
            {"dimension": "3x2", "price": 315},
            {"dimension": "3x3", "price": 320},
            {"dimension": "3x4", "price": 325},
            {"dimension": "4x1", "price": 315},
            {"dimension": "4x2", "price": 320},
            {"dimension": "4x3", "price": 325},
            {"dimension": "4x4", "price": 330}
        ]
    },
    "Long Sleeve Shirts": {
        "xs": [
            {"dimension": "1x1", "price": 330},
            {"dimension": "1x2", "price": 330},
            {"dimension": "1x3", "price": 335},
            {"dimension": "1x4", "price": 335},
            {"dimension": "2x1", "price": 340},
            {"dimension": "2x2", "price": 340},
            {"dimension": "2x3", "price": 345},
            {"dimension": "2x4", "price": 345},
            {"dimension": "3x1", "price": 350},
            {"dimension": "3x2", "price": 350},
            {"dimension": "3x3", "price": 355},
            {"dimension": "3x4", "price": 355},
            {"dimension": "4x1", "price": 335},
            {"dimension": "4x2", "price": 345},
            {"dimension": "4x3", "price": 350},
            {"dimension": "4x4", "price": 355}
        ],
        "s": [
            {"dimension": "1x1", "price": 335},
            {"dimension": "1x2", "price": 340},
            {"dimension": "1x3", "price": 345},
            {"dimension": "1x4", "price": 350},
            {"dimension": "2x1", "price": 340},
            {"dimension": "2x2", "price": 345},
            {"dimension": "2x3", "price": 350},
            {"dimension": "2x4", "price": 355},
            {"dimension": "3x1", "price": 345},
            {"dimension": "3x2", "price": 350},
            {"dimension": "3x3", "price": 355},
            {"dimension": "3x4", "price": 360},
            {"dimension": "4x1", "price": 365},
            {"dimension": "4x2", "price": 370},  // This seems like an error, likely it should be 370
            {"dimension": "4x3", "price": 375},  // This seems like an error, likely it should be 375
            {"dimension": "4x4", "price": 380}   // This seems like an error, likely it should be 380
        ],
        "m": [
            {"dimension": "1x1", "price": 340},
            {"dimension": "1x2", "price": 345},
            {"dimension": "1x3", "price": 350},
            {"dimension": "1x4", "price": 355},
            {"dimension": "2x1", "price": 345},
            {"dimension": "2x2", "price": 350},
            {"dimension": "2x3", "price": 355},
            {"dimension": "2x4", "price": 360},
            {"dimension": "3x1", "price": 350},
            {"dimension": "3x2", "price": 355},
            {"dimension": "3x3", "price": 360},
            {"dimension": "3x4", "price": 365},
            {"dimension": "4x1", "price": 355},
            {"dimension": "4x2", "price": 360},
            {"dimension": "4x3", "price": 365},
            {"dimension": "4x4", "price": 370}
        ],
        "l": [
            {"dimension": "1x1", "price": 345},
            {"dimension": "1x2", "price": 350},
            {"dimension": "1x3", "price": 355},
            {"dimension": "1x4", "price": 360},
            {"dimension": "2x1", "price": 350},
            {"dimension": "2x2", "price": 355},
            {"dimension": "2x3", "price": 360},
            {"dimension": "2x4", "price": 365},
            {"dimension": "3x1", "price": 355},
            {"dimension": "3x2", "price": 360},
            {"dimension": "3x3", "price": 365},
            {"dimension": "3x4", "price": 370},
            {"dimension": "4x1", "price": 360},
            {"dimension": "4x2", "price": 365},
            {"dimension": "4x3", "price": 370},
            {"dimension": "4x4", "price": 375}
        ],
        "xl": [
            {"dimension": "1x1", "price": 350},
            {"dimension": "1x2", "price": 355},
            {"dimension": "1x3", "price": 360},
            {"dimension": "1x4", "price": 365},
            {"dimension": "2x1", "price": 355},
            {"dimension": "2x2", "price": 360},
            {"dimension": "2x3", "price": 365},
            {"dimension": "2x4", "price": 370},
            {"dimension": "3x1", "price": 360},
            {"dimension": "3x2", "price": 365},
            {"dimension": "3x3", "price": 370},
            {"dimension": "3x4", "price": 375},
            {"dimension": "4x1", "price": 365},
            {"dimension": "4x2", "price": 370},
            {"dimension": "4x3", "price": 375},
            {"dimension": "4x4", "price": 380}
        ],
        "2xl": [
            {"dimension": "1x1", "price": 355},
            {"dimension": "1x2", "price": 360},
            {"dimension": "1x3", "price": 365},
            {"dimension": "1x4", "price": 370},
            {"dimension": "2x1", "price": 360},
            {"dimension": "2x2", "price": 365},
            {"dimension": "2x3", "price": 370},
            {"dimension": "2x4", "price": 375},
            {"dimension": "3x1", "price": 365},
            {"dimension": "3x2", "price": 370},
            {"dimension": "3x3", "price": 375},
            {"dimension": "3x4", "price": 380},
            {"dimension": "4x1", "price": 370},
            {"dimension": "4x2", "price": 375},
            {"dimension": "4x3", "price": 380},
            {"dimension": "4x4", "price": 390}
        ]
    },
    "Polo Shirts": {
        "xs": [
            {"dimension": "1x1", "price": 330},
            {"dimension": "1x2", "price": 330},
            {"dimension": "1x3", "price": 335},
            {"dimension": "1x4", "price": 335},
            {"dimension": "2x1", "price": 340},
            {"dimension": "2x2", "price": 340},
            {"dimension": "2x3", "price": 345},
            {"dimension": "2x4", "price": 345},
            {"dimension": "3x1", "price": 350},
            {"dimension": "3x2", "price": 350},
            {"dimension": "3x3", "price": 355},
            {"dimension": "3x4", "price": 355},
            {"dimension": "4x1", "price": 335},
            {"dimension": "4x2", "price": 345},
            {"dimension": "4x3", "price": 350},
            {"dimension": "4x4", "price": 355}
        ],
        "s": [
            {"dimension": "1x1", "price": 335},
            {"dimension": "1x2", "price": 340},
            {"dimension": "1x3", "price": 345},
            {"dimension": "1x4", "price": 350},
            {"dimension": "2x1", "price": 340},
            {"dimension": "2x2", "price": 345},
            {"dimension": "2x3", "price": 350},
            {"dimension": "2x4", "price": 355},
            {"dimension": "3x1", "price": 345},
            {"dimension": "3x2", "price": 350},
            {"dimension": "3x3", "price": 355},
            {"dimension": "3x4", "price": 360},
            {"dimension": "4x1", "price": 365},
            {"dimension": "4x2", "price": 370},  // This seems like an error, likely it should be 370
            {"dimension": "4x3", "price": 375},  // This seems like an error, likely it should be 375
            {"dimension": "4x4", "price": 380}   // This seems like an error, likely it should be 380
        ],
        "m": [
            {"dimension": "1x1", "price": 340},
            {"dimension": "1x2", "price": 345},
            {"dimension": "1x3", "price": 350},
            {"dimension": "1x4", "price": 355},
            {"dimension": "2x1", "price": 345},
            {"dimension": "2x2", "price": 350},
            {"dimension": "2x3", "price": 355},
            {"dimension": "2x4", "price": 360},
            {"dimension": "3x1", "price": 350},
            {"dimension": "3x2", "price": 355},
            {"dimension": "3x3", "price": 360},
            {"dimension": "3x4", "price": 365},
            {"dimension": "4x1", "price": 355},
            {"dimension": "4x2", "price": 360},
            {"dimension": "4x3", "price": 365},
            {"dimension": "4x4", "price": 370}
        ],
        "l": [
            {"dimension": "1x1", "price": 345},
            {"dimension": "1x2", "price": 350},
            {"dimension": "1x3", "price": 355},
            {"dimension": "1x4", "price": 360},
            {"dimension": "2x1", "price": 350},
            {"dimension": "2x2", "price": 355},
            {"dimension": "2x3", "price": 360},
            {"dimension": "2x4", "price": 365},
            {"dimension": "3x1", "price": 355},
            {"dimension": "3x2", "price": 360},
            {"dimension": "3x3", "price": 365},
            {"dimension": "3x4", "price": 370},
            {"dimension": "4x1", "price": 360},
            {"dimension": "4x2", "price": 365},
            {"dimension": "4x3", "price": 370},
            {"dimension": "4x4", "price": 375}
        ],
        "xl": [
            {"dimension": "1x1", "price": 350},
            {"dimension": "1x2", "price": 355},
            {"dimension": "1x3", "price": 360},
            {"dimension": "1x4", "price": 365},
            {"dimension": "2x1", "price": 355},
            {"dimension": "2x2", "price": 360},
            {"dimension": "2x3", "price": 365},
            {"dimension": "2x4", "price": 370},
            {"dimension": "3x1", "price": 360},
            {"dimension": "3x2", "price": 365},
            {"dimension": "3x3", "price": 370},
            {"dimension": "3x4", "price": 375},
            {"dimension": "4x1", "price": 365},
            {"dimension": "4x2", "price": 370},
            {"dimension": "4x3", "price": 375},
            {"dimension": "4x4", "price": 380}
        ],
        "2xl": [
            {"dimension": "1x1", "price": 355},
            {"dimension": "1x2", "price": 360},
            {"dimension": "1x3", "price": 365},
            {"dimension": "1x4", "price": 370},
            {"dimension": "2x1", "price": 360},
            {"dimension": "2x2", "price": 365},
            {"dimension": "2x3", "price": 370},
            {"dimension": "2x4", "price": 375},
            {"dimension": "3x1", "price": 365},
            {"dimension": "3x2", "price": 370},
            {"dimension": "3x3", "price": 375},
            {"dimension": "3x4", "price": 380},
            {"dimension": "4x1", "price": 370},
            {"dimension": "4x2", "price": 375},
            {"dimension": "4x3", "price": 380},
            {"dimension": "4x4", "price": 390}
        ]
    },
    "Tank Tops": {
        "xs": [
            {"dimension": "1x1", "price": 100},
            {"dimension": "1x2", "price": 105},
            {"dimension": "1x3", "price": 110},
            {"dimension": "1x4", "price": 115},
            {"dimension": "2x1", "price": 105},
            {"dimension": "2x2", "price": 110},
            {"dimension": "2x3", "price": 115},
            {"dimension": "2x4", "price": 120},
            {"dimension": "3x1", "price": 110},
            {"dimension": "3x2", "price": 115},
            {"dimension": "3x3", "price": 120},
            {"dimension": "3x4", "price": 125},
            {"dimension": "4x1", "price": 115},
            {"dimension": "4x2", "price": 120},
            {"dimension": "4x3", "price": 125},
            {"dimension": "4x4", "price": 130}
        ],
        "s": [
            {"dimension": "1x1", "price": 110},
            {"dimension": "1x2", "price": 115},
            {"dimension": "1x3", "price": 120},
            {"dimension": "1x4", "price": 125},
            {"dimension": "2x1", "price": 115},
            {"dimension": "2x2", "price": 120},
            {"dimension": "2x3", "price": 125},
            {"dimension": "2x4", "price": 130},
            {"dimension": "3x1", "price": 120},
            {"dimension": "3x2", "price": 125},
            {"dimension": "3x3", "price": 130},
            {"dimension": "3x4", "price": 135},
            {"dimension": "4x1", "price": 125},
            {"dimension": "4x2", "price": 130},
            {"dimension": "4x3", "price": 135},
            {"dimension": "4x4", "price": 140}
        ],
        "m": [
            {"dimension": "1x1", "price": 120},
            {"dimension": "1x2", "price": 125},
            {"dimension": "1x3", "price": 130},
            {"dimension": "1x4", "price": 135},
            {"dimension": "2x1", "price": 125},
            {"dimension": "2x2", "price": 130},
            {"dimension": "2x3", "price": 135},
            {"dimension": "2x4", "price": 140},
            {"dimension": "3x1", "price": 130},
            {"dimension": "3x2", "price": 135},
            {"dimension": "3x3", "price": 140},
            {"dimension": "3x4", "price": 150},
            {"dimension": "4x1", "price": 135},
            {"dimension": "4x2", "price": 140},
            {"dimension": "4x3", "price": 145},
            {"dimension": "4x4", "price": 150}
        ],
        "l": [
            {"dimension": "1x1", "price": 125},
            {"dimension": "1x2", "price": 130},
            {"dimension": "1x3", "price": 135},
            {"dimension": "1x4", "price": 140},
            {"dimension": "2x1", "price": 130},
            {"dimension": "2x2", "price": 135},
            {"dimension": "2x3", "price": 140},
            {"dimension": "2x4", "price": 145},
            {"dimension": "3x1", "price": 135},
            {"dimension": "3x2", "price": 140},
            {"dimension": "3x3", "price": 145},
            {"dimension": "3x4", "price": 150},
            {"dimension": "4x1", "price": 140},
            {"dimension": "4x2", "price": 145},
            {"dimension": "4x3", "price": 150},
            {"dimension": "4x4", "price": 155}
        ],
        "xl": [
            {"dimension": "1x1", "price": 130},
            {"dimension": "1x2", "price": 135},
            {"dimension": "1x3", "price": 140},
            {"dimension": "1x4", "price": 145},
            {"dimension": "2x1", "price": 135},
            {"dimension": "2x2", "price": 140},
            {"dimension": "2x3", "price": 145},
            {"dimension": "2x4", "price": 150},
            {"dimension": "3x1", "price": 140},
            {"dimension": "3x2", "price": 145},
            {"dimension": "3x3", "price": 150},
            {"dimension": "3x4", "price": 155},
            {"dimension": "4x1", "price": 145},
            {"dimension": "4x2", "price": 150},
            {"dimension": "4x3", "price": 155},
            {"dimension": "4x4", "price": 160}
        ],
        "2xl": [
            {"dimension": "1x1", "price": 135},
            {"dimension": "1x2", "price": 140},
            {"dimension": "1x3", "price": 145},
            {"dimension": "1x4", "price": 150},
            {"dimension": "2x1", "price": 140},
            {"dimension": "2x2", "price": 145},
            {"dimension": "2x3", "price": 150},
            {"dimension": "2x4", "price": 155},
            {"dimension": "3x1", "price": 145},
            {"dimension": "3x2", "price": 150},
            {"dimension": "3x3", "price": 155},
            {"dimension": "3x4", "price": 160},
            {"dimension": "4x1", "price": 150},
            {"dimension": "4x2", "price": 155},
            {"dimension": "4x3", "price": 160},
            {"dimension": "4x4", "price": 165}
        ]
    },
    "Hoodies": {
        "xs": [
            {"dimension": "1x1", "price": 330},
            {"dimension": "1x2", "price": 330},
            {"dimension": "1x3", "price": 335},
            {"dimension": "1x4", "price": 335},
            {"dimension": "2x1", "price": 340},
            {"dimension": "2x2", "price": 340},
            {"dimension": "2x3", "price": 345},
            {"dimension": "2x4", "price": 345},
            {"dimension": "3x1", "price": 350},
            {"dimension": "3x2", "price": 350},
            {"dimension": "3x3", "price": 355},
            {"dimension": "3x4", "price": 355},
            {"dimension": "4x1", "price": 335},
            {"dimension": "4x2", "price": 345},
            {"dimension": "4x3", "price": 350},
            {"dimension": "4x4", "price": 355}
        ],
        "s": [
            {"dimension": "1x1", "price": 335},
            {"dimension": "1x2", "price": 340},
            {"dimension": "1x3", "price": 345},
            {"dimension": "1x4", "price": 350},
            {"dimension": "2x1", "price": 340},
            {"dimension": "2x2", "price": 345},
            {"dimension": "2x3", "price": 350},
            {"dimension": "2x4", "price": 355},
            {"dimension": "3x1", "price": 345},
            {"dimension": "3x2", "price": 350},
            {"dimension": "3x3", "price": 355},
            {"dimension": "3x4", "price": 360},
            {"dimension": "4x1", "price": 365},
            {"dimension": "4x2", "price": 270},
            {"dimension": "4x3", "price": 275},
            {"dimension": "4x4", "price": 280}
        ],
        "m": [
            {"dimension": "1x1", "price": 340},
            {"dimension": "1x2", "price": 345},
            {"dimension": "1x3", "price": 350},
            {"dimension": "1x4", "price": 355},
            {"dimension": "2x1", "price": 345},
            {"dimension": "2x2", "price": 350},
            {"dimension": "2x3", "price": 355},
            {"dimension": "2x4", "price": 360},
            {"dimension": "3x1", "price": 350},
            {"dimension": "3x2", "price": 355},
            {"dimension": "3x3", "price": 360},
            {"dimension": "3x4", "price": 365},
            {"dimension": "4x1", "price": 355},
            {"dimension": "4x2", "price": 360},
            {"dimension": "4x3", "price": 365},
            {"dimension": "4x4", "price": 370}
        ],
        "l": [
            {"dimension": "1x1", "price": 345},
            {"dimension": "1x2", "price": 350},
            {"dimension": "1x3", "price": 355},
            {"dimension": "1x4", "price": 360},
            {"dimension": "2x1", "price": 350},
            {"dimension": "2x2", "price": 355},
            {"dimension": "2x3", "price": 360},
            {"dimension": "2x4", "price": 365},
            {"dimension": "3x1", "price": 355},
            {"dimension": "3x2", "price": 360},
            {"dimension": "3x3", "price": 365},
            {"dimension": "3x4", "price": 370},
            {"dimension": "4x1", "price": 360},
            {"dimension": "4x2", "price": 365},
            {"dimension": "4x3", "price": 370},
            {"dimension": "4x4", "price": 375}
        ],
        "xl": [
            {"dimension": "1x1", "price": 350},
            {"dimension": "1x2", "price": 355},
            {"dimension": "1x3", "price": 360},
            {"dimension": "1x4", "price": 365},
            {"dimension": "2x1", "price": 355},
            {"dimension": "2x2", "price": 360},
            {"dimension": "2x3", "price": 365},
            {"dimension": "2x4", "price": 370},
            {"dimension": "3x1", "price": 360},
            {"dimension": "3x2", "price": 365},
            {"dimension": "3x3", "price": 370},
            {"dimension": "3x4", "price": 375},
            {"dimension": "4x1", "price": 365},
            {"dimension": "4x2", "price": 370},
            {"dimension": "4x3", "price": 375},
            {"dimension": "4x4", "price": 380}
        ],
        "2xl": [
            {"dimension": "1x1", "price": 355},
            {"dimension": "1x2", "price": 360},
            {"dimension": "1x3", "price": 365},
            {"dimension": "1x4", "price": 370},
            {"dimension": "2x1", "price": 360},
            {"dimension": "2x2", "price": 365},
            {"dimension": "2x3", "price": 370},
            {"dimension": "2x4", "price": 375},
            {"dimension": "3x1", "price": 365},
            {"dimension": "3x2", "price": 370},
            {"dimension": "3x3", "price": 375},
            {"dimension": "3x4", "price": 380},
            {"dimension": "4x1", "price": 370},
            {"dimension": "4x2", "price": 375},
            {"dimension": "4x3", "price": 380},
            {"dimension": "4x4", "price": 390}
        ]
    }
}

